version: '2'
services:
  socketservice:
    extends:
      file: common.yml
      service: socketservice
    build:
      context: ./test/
      dockerfile: Dockerfile
      
  dockerapp:
    extends:
      file: common.yml
      service: dockerapp
    build: .
  
  

  redis:
    extends:
      file: common.yml
      service: redis
