version: '2'
services:
  dockerapp:
    extends:
      file: common.yml
      service: dockerapp
    build: .
  
  socketservice:
    extends:
      file: common.yml
      service: socketservice
    build: Dockerfile-socket

  redis:
    extends:
      file: common.yml
      service: redis
